apiVersion: apps/v1
kind: Deployment
metadata:
  name: bearer
  labels:
    app.kubernetes.io/name: bearer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bearer
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bearer
    spec:
      serviceAccountName: bearer
      containers:
      - name: bearer
        image: bearer
        imagePullPolicy: IfNotPresent
        command:
        - /contour-authserver
        args:
        - bearer
        - --address=:9443
        - --tls-ca-path=/tls/ca.crt
        - --tls-cert-path=/tls/tls.crt
        - --tls-key-path=/tls/tls.key
        ports:
        - name: auth
          containerPort: 9443
          protocol: TCP
        volumeMounts:
        - name: tls
          mountPath: /tls
          readOnly: true
        resources:
          limits:
            cpu: 100m
            memory: 90Mi
      volumes:
      - name: tls
        secret:
          secretName: bearer

---

apiVersion: v1
kind: Service
metadata:
  name: bearer
  labels:
    app.kubernetes.io/name: bearer
spec:
  ports:
  - name: auth
    protocol: TCP
    port: 9443
    targetPort: 9443
  selector:
    app.kubernetes.io/name: bearer
  type: ClusterIP
